vich_uploader:
  db_driver: orm

  mappings:
    product_image:
      uri_prefix: /uploads/projects
      upload_destination: '%kernel.project_dir%/public/uploads/projects'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
